if: branch = master OR tag IS present
sudo: true # give us 7.5GB and >2 bursted cores.
script:
    - make travis_${TRAVIS_EVENT_TYPE}
after_failure:
    # Copy any data from failed tests to S3.
    - aws --region us-west-2 s3 cp --recursive "${PULUMI_FAILED_TESTS_DIR}" "s3://eng.pulumi.com/travis-logs/${TRAVIS_REPO_SLUG}/${TRAVIS_JOB_NUMBER}/failures"
notifications:
    webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
