[[constraint]]
  version = "v1.10.1"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.3.0"
  name = "github.com/pulumi/pulumi-openstack"

[prune]
  go-tests = true
  unused-packages = true
