[[constraint]]
  version = "v0.17.17"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v0.18.3"
  name = "github.com/pulumi/pulumi-digitalocean"

[prune]
  go-tests = true
  unused-packages = true
