[[constraint]]
  version = "v1.10.1"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.6.0"
  name = "github.com/pulumi/pulumi-digitalocean"

[prune]
  go-tests = true
  unused-packages = true
