[[constraint]]
  version = "v1.0.0"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.1.0"
  name = "github.com/pulumi/pulumi-alicloud"

[prune]
  go-tests = true
  unused-packages = true
