name: Run Tests on a PR Command
on:
  repository_dispatch:
    types: [fork-command]
jobs:
  fork:
    runs-on: ubuntu-latest
    steps:
      - name: Install DotNet 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python Deps
        run: |
          pip3 install pyenv-win
          pip3 install pipenv
      - name: Set Build Env Vars
        uses: allenevans/set-env@v1.0.0
        with:
          PULUMI_TEST_OWNER: "moolumi"
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
          BLACK_LISTED_TESTS: "go,alicloud,azure,digitalocean,kubernetes,openstack,packet"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get dependencies non-windows
        run: make ensure
      - name: Run tests
        run: |
          make test_templates
      - name: Update with Result
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
