name: Test Forked PR Command
on:
  issue_comment:
    # We want to be able to run the command when a comment has been added
    # to the pull-request
    types: [created, edited]

jobs:
  runForkedBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Build
        uses: ./
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: fork-command
          permission: write
          issue-type: pull-request
