name: Run Tests on a PR of the Templates repo
on:
  repository_dispatch:
    types: [run-templates-command]

env:
  PULUMI_TEST_OWNER: "moolumi"
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  AWS_REGION: "us-west-2"
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
  BLACK_LISTED_TESTS: "alicloud,azure,digitalocean,kubernetes,openstack,packet"
  PULUMI_API: https://api.pulumi-staging.io
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install DotNet 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - run: go env
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python Deps
        run: |
          pip3 install pyenv-win
          pip3 install pipenv
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
          role-session-name: templates@githubActions
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Get dependencies non-windows
        run: make ensure
      - name: Run tests
        run: |
          make test_templates
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      - name: Update with Result
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Please view the results of the PR Build [Here][1]

            [1]: ${{ steps.vars.outputs.run-url }}
